### ISSUE TITLE
Walk not showing up on City Page

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#120]
Belleville, ON -- walk "Jane's Ride" appears to be published (Unpublish is not checked; I tried going into Edit, making a small change & hitting Publish) but does not show up on the City Page. Same problem happening in Charlotte, Calgary, others.

**Comment by janeswalk** [comment]
Julie in Calgary may have figured out what is causing this:
"I’m thinking  that the publishing problem people think they’re having is that they’re not entering their date.
Or rather, they are but they don’t hit the ADD DATE button before hitting NEXT. (see below)
So, they think they’ve entered their date but haven’t.
And our accounts tell us it’s published but it doesn’t appear."
![image001](https://cloud.githubusercontent.com/assets/8632559/6694044/bae44128-ccad-11e4-8aa4-31f26e553c7d.png)

**Comment by jkoudys** [comment]
Ah, that would make sense, because it's listing the walks by date
everywhere now. I don't think they'll show up at all if you don't have a
date on them, anywhere but the profile page that is.

Since it's a mistake enough people seem to be making, perhaps the UI here
needs to be rethought. Maybe there will always be a date set in the table,
and we remove the 'add date' button completely. Instead, the table could
have a blank row at the bottom that says "add date". You'd select a date
from the table and can modify it, exactly like how you select a marker on
the map and can modify it, then you see the details update in the table
below as you edit it

**Comment by janeswalk** [comment]
That might help -- I'm finding also that a lot of people are tripped up by the fact that you have to click "add Date" and then ALSO "Save" -- they think Add Date has done the job, then e-mail me asking why the date won't "take."

**Comment by jkoudys** [comment]
There were secondary issues around usability and not setting dates; much of this will probably be addressed by our pending design review.
