### ISSUE TITLE
COs can't publish edits to city page

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#123]
When logged in as City Organizer (I tried logging in as Greg Vann & editing the Brisbane page), changes to Long and Short Description can be saved, but hitting "Publish" gets a blank screen reading "Access Denied"

**Comment by jkoudys** [comment]
This has nothing to do with permissions, and the city gets updated just fine. The only problem is the URL it redirects you to to go back to the page looks like this:

    http://janeswalk.org/index.php/?cID=536

Apparently our webserver's getting confused by the extra `/` in there, since this is perfectly okay:

    http://janeswalk.org/index.php?cID=536

I've updated our webserver config to automatically remove the trailing slash.
