### ISSUE TITLE
Save/Publish button not accessible in Chrome

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#130]
Can't access Save button in the Edit popup window. Can sometimes work around this by going to Fullscreen but not always

![editmode](https://cloud.githubusercontent.com/assets/8632559/6734160/e356c9de-ce2c-11e4-8528-9b2917016c13.jpg)

**Comment by jkoudys** [comment]
I think it's best we just leave that alone - you can get around it by making your window taller if needed. This edit menu is only used internally, and is completely different in newer versions of concrete5. It's only an issue for us because the header + footer cover it, so changing that might cause problems elsewhere on the site that are hard to test for.

Workaround for now: just un-maximize your window, drag it so the bottom's off the screen, drag it taller from the top; rinse and repeat until it's tall enough for the dialog.
