### ISSUE TITLE
Walk page at top right lists both this year’s walk date and last year's

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#132]
Fear that this could confuse people who don't pay attention to the year. We need to keep the data, but show only upcoming dates.

**Comment by jkoudys** [comment]
Should it still show somewhere on the page, e.g. with a 'Past Dates' heading? I think some people might still want to find a walk they went on last year and know it's the same one.

**Comment by janeswalk** [comment]
When you create the search slider, that will let people choose by date-- that way people can browse walks from past years. If they update their walk pages (route/story) it may not be the same one anyway.

**Comment by jkoudys** [comment]
right but they won't see it on the walk page itself. Analytics show lots of people will bookmark walks, so if someone's going back to a walk from a bookmark, link from facebook, etc. it'd be nice to see the past dates there (they'd know it was the same walk as last time since they'd remember the date). Not sure if this matters much for people wanting to repeat a walk, but if they're recommending to a friend it could help.

**Comment by janeswalktech** [comment]
Resolved to move previous dates to the bottom of walk pages.

**Comment by jkoudys** [comment]
done.
