### ISSUE TITLE
Multiple walk leader names on preview card

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#143]
For this walk, names of all walk leaders on the Team appear in header and on preview card:
http://janeswalk.org/canada/calgary/placemaking-calgary-how-have-more-fun-create-community-and-build-better-cities/

For this walk, only one name appears:
http://janeswalk.org/canada/calgary/arts-walk/

I've looked at it in Properties and can't figure out why; can someone tell me? CO would like multiple walk leaders to appear in header/on preview card in all cases.

**Comment by jkoudys** [comment]
Arun's listed as a 'co-walk leader', not a walk leader, that's why it's just Johann's name up there.

This was originally built with a co-walk leader, but I've never really found that a valuable designation -- you can just make multiple walk leaders.

Should I just go ahead and get rid of the 'co-walk leader' role entirely, so nobody chooses it anymore? The two types of walk owners will then be: leader, and organizer.

**Comment by janeswalk** [comment]
Yes -- getting rid of that role would solve the problem, thank you!
