### ISSUE TITLE
JS error on City page

### ISSUE THREAD

**Issue by monting** [jkoudys/janeswalk-web#180]
On http://dev.janeswalk.org/canada/toronto/

Getting JS error:
```
Error instantiating page view CityPageView: ReferenceError: $btn is not defined
    at CityPageView._addCreateWalkEvent (janeswalk.js:41095)
    at new CityPageView (janeswalk.js:41082)
    at routePage (janeswalk.js:119)
    at HTMLDocument.<anonymous> (janeswalk.js:132)
```

**Comment by jkoudys** [comment]
Do you see this one as preventing anything from rendering? The city-page is on track for a full redesign for phase II, and the error there is in a component that we're phasing out (the old system of building the HTML server-side and attaching data to it, instead of the ReactJS approach of building the DOM client-side from raw server data). If it's on a non-breaking path, it'd be easier just to ignore and see it resolved when the new layout is implemented.

**Comment by monting** [comment]
I see hmm... I thought I saw that it was preventing react components from rendering on dev.janeswalk.org, which is not the case now. I probably believed wrong. Sounds completely reasonable to wait.
