### ISSUE TITLE
walk date range filter beginning date not applied

### ISSUE THREAD

**Issue by monting** [jkoudys/janeswalk-web#181]
The default beginning date range appears to not be taken into account, when an end date is chosen.

steps to reproduce:
- Go on a city page with lots of walks in the past. The default beginning date is set automatically on load.
- Set the end date for the date range to a date that is close to now, or in the future.
- The walks shown appear to include all past walks, including walks before the default beginning date.
- Upon setting the beginning date to the same as a default beginning date, the walk list appears to be in order.

**Comment by jkoudys** [comment]
Looks like an error accepting the date properties. The date range with set the string-formatted date in the field correctly, but it errors before it properly sets the filter. As a result, the list will be blank until you've changed it the first time:

```
Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `DateRange`.
```
Still not 100% sure why this should happen, since I'm clearly passing in an onChange (and as you've pointed out, the component does update correctly when you do change it), so I must've missed something; maybe just using a prop that hasn't been initialized yet.
