### ISSUE TITLE
Cache walk model objects

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#2]
Either using the base c5 Cache class, or do in-memory key-value caching with MyDis, of the walk model objects. Now that this is a model, it should be quite quick to serialize/deserialize from cache as a whole, which should speed the walk page load time up significantly.

**Comment by janeswalk** [comment]
I've completely revamped how these models are loaded since writing it, so it's nowhere near as important. Rather than cache the model, I've rewritten the model so it doesn't separately query each individual object (resulting in hundreds of synchronous queries, and way more PHP logic than needed) but simply grabs all the data it needs for the constructor up-front. This has resulted in a remarkable speed increase, and makes it rather pointless to cache individual Walk objects. Caching should instead focus on the JSON we generate from the models, e.g. caching the walk list on a city page.
