### ISSUE TITLE
COs cannot update city page blocks (from profile, or otherwise)

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#87]
When opening the composer as a CO, Editor still says "Block not found. Unable to edit in composer.")

**Comment by jkoudys** [comment]
This appears to be some issue with how c5 manages 'detaching' a block from its page-type defaults. Fortunately this default is just empty, which means we should be able to simply migrate the old content (in its blocks, which can be edited from the 'edit page' button on the top left) to page-attributes. I think blocks are theoretically a better place to do it, but attributes are way simpler and it's too important a place to risk breaking it. Since we give them an edit button that goes to composer, let's use blocks only for non-composer things (eg something advanced users could modify).

I notice that shortdescription and longdescription attributes already exist, and some are set. I have the code there to display them, but let's go through and make sure it's displaying the right data before I deploy.

**Comment by jkoudys** [comment]
I've made the top and sidebar text part of an attribute, not a block. Attributes are a lot safer since they're simply the text it'll display, so there's a lot less complexity therefore less that can break.
